[tool.poetry]
name = "face"
version = "0.1.0"
description = ""
authors = ["jiyuan <wx_76545d85de8e401989c08822c5df4029@git.code.tencent.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
