
env: prod

prog_module: /java_web/cloudcs2mon/pyspace/

linkpath_prefix: /java_web/cloudcs2mon/static/uploadPath/monlink/

out_path: d:\tmp\vedio\
out_prefix: /profile/monvedio/
work_dir: /java_web/cloudcs2mon/static/uploadPath

ai_model_dir: .cache/whisper
# tiny base small medium large-v2 large-v3
ai_model_nm: medium

#img_path: "pic/1-27-0E·LANDKIDS童装秋装新品男女童时尚拼色立领半拉链上衣.png"
#out_img_path: "pic/1-27-0E·LANDKIDS童装秋装新品男女童时尚拼色立领半拉链上衣-check.png"
#db_out_img_path: /profile/monlink