FROM python:3.9-buster

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install ffmpeg libsm6 libxext6 \
    ttf-wqy-microhei libnss3 libx11-xcb1 libasound2 libatk-bridge2.0-0 libgtk-3-0 \
    libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libxkbcommon0 libxslt1.1 libgtk-3-0 libdbus-glib-1-2 -y \
    kde-plasma-desktop \
    libgl1-mesa-dev* build-essential \
    && pip3 install playwright -i https://pypi.tuna.tsinghua.edu.cn/simple \
    &&  playwright install chromium \
    && apt-get clean

